apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-json
spec:
  selector:
    matchLabels:
      app: producer-json
  template:
    metadata:
      labels:
        app: producer-json
        version: "1.0"
    spec:
      containers:
      - name: producer-json
        image: barcz/prod:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: CREATOR_HOST
            value: "0.0.0.0"
          - name: CREATOR_PORT
            value: "8080"
          - name: PRODUCER_HOST
            value: "0.0.0.0"
          - name: PRODUCER_PORT
            value: "8081"
        ports:
        - containerPort: 8080
          name: http
